/**:
  ros__parameters:
    max_vel: 6000.0
    max_brk: 6500.0
    max_str: 2000.0
    thr_kp: 6.5
    thr_ki: 50.0
    thr_kd: 0.0
    br_kp: 150.0
    br_ki: 40.0 #150.0
    br_kd: 0.0
    str_kp: 30.0 # 75.0. 125.0
    str_ki: 0.0
    str_kd: 600.0 # 75.0, 125.0, 500.0
